// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CriarLancamento() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<lancamentos x-data=\"CriarLancamento\" class=\"row\"><form x-ref=\"formAdicionarLancamento\" class=\"p-3\" @submit.prevent=\"submit\"><section class=\"row\"><cadastro after=\"true\" class=\"col-xl col-lg-4 mt-2\"><label>Evento</label> <select x-model=\"modelo.evento\" required><template x-for=\"evento in eventosLancamento\"><option :value=\"evento.value\" x-text=\"evento.label\"></option></template></select></cadastro> <cadastro after=\"true\" class=\"col-xl col-lg-4 mt-2\"><label class=\"text-nowrap\">Natureza da Transação</label> <select x-model=\"modelo.natureza\" required><template x-for=\"nat in naturezas\"><option :value=\"nat\" x-text=\"nat\"></option></template></select></cadastro> <cadastro after=\"true\" class=\"col-xl col-lg-4 mt-2\"><label class=\"text-nowrap\">Meio Financeiro</label> <select x-model=\"modelo.meioFinanceiro\" required><template x-for=\"meio in meios_financeiros\"><option :value=\"meio\" x-text=\"meio\"></option></template></select></cadastro> <cadastro class=\"col-xl col-lg-4 mt-2\"><label>Valores</label> <before>R$</before> <input type=\"number\" step=\"0.0001\" x-model=\"modelo.valores\" required></cadastro> <cadastro class=\"col-lg col-md mt-2\"><label>Vencimento</label> <input type=\"datetime-local\" x-model=\"modelo.vencimento\" required></cadastro></section><section class=\"row\"><cadastro class=\"col-md mt-2\"><label>Descrição</label> <textarea rows=\"3\" x-model=\"modelo.descricao\" placeholder=\"Adicione uma descrição sobre a transação\" type=\"text\" maxlength=\"500\" required></textarea></cadastro></section><section><button :disabled=\"criando\" class=\"col-4 offset-8 mt-2 btn btn-dark d-inline-flex align-items-center justify-content-center\"><span class=\"px-2\">Submit</span> <span :class=\"criando &amp;&amp; &#39;visible&#39;\" class=\"spinner-border spinner-border-sm fade-opacity\" aria-hidden=\"true\"></span></button></section></form></lancamentos>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func ListarLancamentos() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<lancamentos x-data=\"ListarLancamentos\" class=\"py-2\"><filtros class=\"row py-3\"><filtro class=\"col-md\"><label>Intervalo</label> <input type=\"date\" x-model=\"filtros.intervalo\"></filtro> <filtro class=\"col-md\"><label>Descrição</label> <input type=\"text\" x-model=\"filtros.descricao\"></filtro> <filtro class=\"col-md\"><label>Chave</label> <input type=\"text\" x-model=\"filtros.chave\"></filtro> <filtro class=\"col-md\" after=\"true\"><label>Evento</label> <select x-model=\"filtros.evento\"><option value=\"\">Selecione</option><template x-for=\"evento in eventosLancamento\"><option value=\"evento.value\" x-text=\"evento.label\"></option></template></select></filtro></filtros>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = headersListaLancamentos().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<resultados><template x-for=\"(lancamento, index) in lancamentos\" :key=\"`${lancamento.id}-${lancamento.chave}`\"><div class=\"col-12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Lancamento().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></template></resultados></lancamentos>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func headersListaLancamentos() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"border-bottom border-top border-2 border-dark row p-2\"><div class=\"row ps-2 pe-0\"><div class=\"col-4 d-flex\"><div class=\"col-9\">timestamp</div><div class=\"col-3 text-center\">evento</div></div><div class=\"col-5\">detalhes</div><div class=\"col-2 text-end ms-2 pe-0\">valores</div><div class=\"col-1 ps-0\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func Lancamento() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<lancamento x-data=\"Lancamento(lancamento)\" class=\"row py-3\"><div class=\"col-4 d-flex fs-06rem\"><div class=\"col-9 d-flex align-items-center\"><div x-text=\"dayjs.utc(value.timestamp).tz(&#39;America/Sao_Paulo&#39;).format(&#39;LLLL&#39;)\"></div></div><div class=\"col-3 fw-medium fs-06rem d-flex align-items-center justify-content-center\"><span x-text=\"evento\"></span></div></div><div class=\"col-5\"><div x-text=\"value.descricao\"></div><div class=\"text-secondary fs-06rem\" x-text=\"value.chave\"></div></div><div class=\"col-2 d-flex justify-content-end\"><div class=\"pe-2 d-flex flex-column align-items-end\"><div class=\"text-end\" x-text=\"valores.exibicao\"></div><tag :class=\"`${natureza.cor} fs-06rem text-end`\" x-text=\"natureza.exibicao\"></tag></div></div><div class=\"col-1 text-end\"><button class=\"btn btn-lighter bi bi-card-list\"></button></div></lancamento>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func Lancamentos() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = CriarLancamento().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ListarLancamentos().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
